### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by carlosnewmusic** [xbelanch/OBS4Pi#4]
![imagen](https://user-images.githubusercontent.com/19379457/113604632-d4152f00-9645-11eb-824b-c4cf6d47af6b.png)
I would put the compilation errors, but they have been deleted by the script.

**Comment by xbelanch** [comment]
At the moment, that script is debian-centric. In fact, Raspberry Pi OS or previously called Raspbian is a derivative of Debian. On the other hand I guess you're trying to execute it on Manjaro I guess. Manjaro is a derivative of Arch and that distro works with Pacman as a package manager instead of apt. Have you previously installed the bunch of dev libraries needed (appear at the beginning of the script) to compile all the stuff?

**Comment by carlosnewmusic** [comment]
> At the moment, that script is debian-centric. In fact, Raspberry Pi OS or previously called Raspbian is a derivative of Debian. On the other hand I guess you're trying to execute it on Manjaro I guess. Manjaro is a derivative of Arch and that distro works with Pacman as a package manager instead of apt. Have you previously installed the bunch of dev libraries needed (appear at the beginning of the script) to compile all the stuff?

I use armbian. also based on Debian, and I did install all the dev libraries put in the script.

**Comment by xbelanch** [comment]
>I use armbian. also based on Debian, and I did install all the dev libraries put in the script.

Oh, I understood you're using Manjaro because the terminal screenshoot of the first post. On the other hand, can you execute the script in this way and share the output log (pastebin would be an option)?:

`./build.sh 2>&1 | tee log.txt`

**Comment by GreenBOTT** [comment]
[log.txt](https://github.com/xbelanch/OBS4Pi/files/6310303/log.txt)
Here is a log from what i got after running this script on my raspberry pi, and it seems to work fine, until after it finished, i cannot find obs anywhere, maybe i am just a bit dumb, but is there maybe some problem ? (ps: pretty new to raspberry pi in gerneral)

**Comment by xbelanch** [comment]
error raises at this point (at the very end of the log):

`CEF Not found -- set CEF_ROOT_DIR or set BUILD_BROWSER=OFF.`

This problem is related to OBS support for browser source plugin on Pi, well commented on this thread (https://obsproject.com/forum/threads/obs-raspberry-pi-build-instructions.115739/). 

I'm wondering if you have added this option (-DBUILD_BROWSER=1) to OBS's cmake preparing building.

**Comment by xbelanch** [comment]
error raises at this point (at the very end of the log):

`CEF Not found -- set CEF_ROOT_DIR or set BUILD_BROWSER=OFF.`

This problem is related to OBS support for browser source plugin on Pi, well commented on this thread (https://obsproject.com/forum/threads/obs-raspberry-pi-build-instructions.115739/). 

At this point, it seems that BUILD_BROWSER directive isn't change the result and I didn't found any workaround to solve this issue.
